### ISSUE TITLE
Aggiungere GA

### ISSUE THREAD

**Issue by CatMonster** [PowsUp/landing-page#6]

**Comment by JaxzTW** [comment]
`
<script async src="https://www.googletagmanager.com/gtag/js?id=G-RXTKS3T2XL"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-RXTKS3T2XL');
</script>
`

**Comment by JaxzTW** [comment]
https://www.kevinzunigacuellar.com/blog/google-analytics-in-astro/
